spring.application.name=gerenciador-de-tarefas
spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciar-tarefas-db
spring.datasource.username=postgres
spring.datasource.password=8569

# gerar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update